### ISSUE TITLE
feeling bad

### ISSUE THREAD

**Issue by guybedford** [Seikho/designco#1]
Sorry to barge in here, but I'm always interested to hear negative feedback. What sucks specifically?

It looks like you might have needed to set a `baseURL` in the package.json directories to the public directory to share the package.json with npm, was that the frustrating part?

**Comment by Seikho** [comment]
Regardless of the jspm config in `package.json`, the module loader would prefix ajax `GET` requests with the full jspm_package directory (`front/jspm_packages`). This would also occur when a `baseUrl` was present in config.

I should also add that the commit comment is definitely an over-reaction. That was how I felt after an hour of experimenting with config and re-installing all of the modules (`jspm install`) to try and get this working with my particular project structure. My intention was to look at the source and find a better solution than the one I have presently.

**Comment by guybedford** [comment]
If you had added `{ "directories": { "baseURL": "front" } }` to the package.json this provides the "server baseURL", that should then not add the `front/jspm_packages` part as the baseURL needs to represent the same folder between client and server as a shared reference point. This is attempted to be communicated when running `jspm init -p`.

Certainly, completely understand it was your own frustration and not directed!

**Comment by Seikho** [comment]
I'm gonna go and tag this `pebkac`. I was misinterpreting the `init` prompts.  
I **think** when I did have a `baseURL: front` in packages.json, I also had a `System.config({ ... "baseURL: front" ... })` as well. I'm pretty sure this was responsible for the URL prefixing.

I'll have to double check at home. I most likely have a much older version of jspm-cli at home which could also be playing a part here. Also, my work proxy is stopping me from going any further since it seems to be responsible for this error when initialising/installing:

```
err  Error: incorrect header check
         at Zlib._handle.onerror (zlib.js:366:17)
```

Not a lot I can do about that right now.

Thanks for chiming in. Was very unexpected and very helpful.

**Comment by Seikho** [comment]
Also, @guybedford, how did you stumble across the commit(s)?

**Comment by lorezzed** [comment]
Sorry @guybedford this is off-topic, but out of curiosity, how did you come across the commit mentioning jspm? Using a github api? I'm liking jspm with angular so far :)

**Comment by guybedford** [comment]
Glad it is making some sense. One thing that has become clear is that we should always set `directories.baseURL` in the package.json instead of having an invisible default trying not to pollute the package.json.

@lorezzed this came up under https://twitter.com/bathroomcommits when searching for SystemJS.

**Comment by lorezzed** [comment]
That's fantastic, cheers =D

**Comment by Seikho** [comment]
What a great read those feeds are!

Thanks for that, @guybedford. I can confirm that I was definitely putting in a client base URL in `config.js`. Sorry for making you feel bad :rose:

**Comment by guybedford** [comment]
Sure, glad it's making some sense!
